TASK: EFN_hm10_EFPN_NoBasedCLS_Focal_C3_256Cst100_32FXRayv2_SAM(Adam)_ADV_Era1_OutSigmoid_1e7_boost500_UnFZ
PRECISION: float64
METRICS_BASE: binary
SEED: 317
DATA_RELOAD: True
DATASET:
  type: HeatmapFaceForensic
  DATA_TYPE: image
  TRAIN: True #Switch to True for training mode, False for testing mode
  COMPRESSION: c0
  IMAGE_SUFFIX: png
  NUM_WORKERS: 28
  PIN_MEMORY: True
  IMAGE_SIZE: [384, 384]
  HEATMAP_SIZE: [96, 96] #[IMAGE_SIZE//4, IMAGE_SIZE//4]
  SIGMA: 2
  ADAPTIVE_SIGMA: True
  HEATMAP_TYPE: gaussian
  SPLIT_IMAGE: False
  DATA:
    TYPE: frames
    SAMPLES_PER_VIDEO: 
      ACTIVE: True
      TRAIN: 32 # Dynamically random number of frames in each epoch
      VAL: 32
      TEST: 32
      DIST: [1., 1.] # Distribution of Real, Fake - 1.,1. by default
    TRAIN:
      NAME: FF++ # This field to define datasets that can be used to train/in-dataset/cross-dataset evaluation
      ROOT: /home/users/XXX/data/FaceForensics++/c0/
      # ROOT: /data/deepfake_cluster/datasets_df/FaceForensics++/c0/
      FROM_FILE: True
      FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
      # ANNO_FILE: train/frames/FaceXRay/train_FF_FaceXRay.json
      ANNO_FILE: processed_data/c0/dynamic_trainBI_FFv2.json
      LABEL_FOLDER: [real, fake]
    VAL:
      NAME: FF++ # This field to define datasets that can be used to train/in-dataset/cross-dataset evaluation
      ROOT: /home/users/XXX/data/FaceForensics++/c0/
      FROM_FILE: True
      FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures] # Choosing Deepfake techniques to be loaded for dataloader
      # ANNO_FILE: val/frames/FaceXRay/val_FF_FaceXRay.json
      ANNO_FILE: processed_data/c0/dynamic_valBI_FFv2.json
      LABEL_FOLDER: [real, fake]
    TEST:
      NAME: FF++
      # ROOT: /home/users/XXX/data/FaceForensics++/c0/
      ROOT: /project/home/p200249/XXX/FaceForensics++/c23/
      # ROOT: /home/users/XXX/data/Celeb-DFv1/
      # ROOT: /data/deepfake_cluster/datasets_df/Celeb-DFv1/
      # ROOT: /home/users/XXX/data/Celeb-DFv2/
      # ROOT: /project/home/p200249/XXX/Celeb-DFv2/
      # ROOT: /home/users/XXX/data/DFDCP/
      # ROOT: /home/users/XXX/data/DFDC/
      # ROOT: /project/home/p200249/XXX/DFDC/
      # ROOT: /home/users/XXX/data/DFD/
      # ROOT: /home/users/XXX/data/DFW/
      FROM_FILE: False
      # FAKETYPE: [original, Deepfakes, Face2Face, FaceSwap, NeuralTextures]
      # FAKETYPE: [frames_BW_5/original, frames_BW_5/Deepfakes, frames_BW_5/Face2Face, frames_BW_5/FaceSwap, frames_BW_5/NeuralTextures]
      FAKETYPE: [frames_JPEG_1/original, frames_JPEG_1/Deepfakes, frames_JPEG_1/Face2Face, frames_JPEG_1/FaceSwap, frames_JPEG_1/NeuralTextures, 
                frames_JPEG_2/original, frames_JPEG_2/Deepfakes, frames_JPEG_2/Face2Face, frames_JPEG_2/FaceSwap, frames_JPEG_2/NeuralTextures,
                frames_JPEG_3/original, frames_JPEG_3/Deepfakes, frames_JPEG_3/Face2Face, frames_JPEG_3/FaceSwap, frames_JPEG_3/NeuralTextures,
                frames_JPEG_4/original, frames_JPEG_4/Deepfakes, frames_JPEG_4/Face2Face, frames_JPEG_4/FaceSwap, frames_JPEG_4/NeuralTextures,
                frames_JPEG_5/original, frames_JPEG_5/Deepfakes, frames_JPEG_5/Face2Face, frames_JPEG_5/FaceSwap, frames_JPEG_5/NeuralTextures]
      # FAKETYPE: [Celeb-real, Celeb-synthesis, YouTube-real]
      # FAKETYPE: [method_A, method_B, original_videos]
      # FAKETYPE: [fake, real]
      # FAKETYPE: [DeepFakeDetection_original, DeepFakeDetection]
      # FAKETYPE: [real_test, fake_test]
      # ANNO_FILE: FaceXRay/test/test_FF_Xray.json
      LABEL_FOLDER: [real, fake]
  TRANSFORM:
    geometry:
      type: GeometryTransform
      resize: [384, 384, 0] #h, w, p=probability. If no affine transform, set p=1
      normalize: 0
      horizontal_flip: 0.5
      cropping: [0.15, 0.5] #Format: [crop_limit, prob]
      scale: [0.15, 0.5] #Format: [scale_limit, prob]
      rand_erasing: [0.5, 1] #Format: [p, max_count]
    color:
      type: ColorJitterTransform
      clahe: 0.0
      colorjitter: 0.3
      gaussianblur: 0.3
      gaussnoise: 0.3
      jpegcompression: [0.5, 40, 100] # prob, lower and upper quality respectively
      rgbshift: 0.3
      randomcontrast: 0.0
      randomgamma: 0.5
      randombrightness: 1
      huesat: 1
    normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
  DEBUG: False
  DYNAMIC_FXRAY: True
MODEL:
  type: PoseEfficientNet
  model_name: efficientnet-b4
  num_layers: B4
  include_top: False
  include_hm_decoder: True
  head_conv: 64
  use_c2: False
  use_c3: True
  use_c4: True
  use_c51: True
  efpn: True
  tfpn: False
  se_layer: False
  norm_c2: False
  heads:
    hm: 1
    cls: 1
    cstency: 256
  INIT_WEIGHTS:
    pretrained: True
    advprop: True
TRAIN:
  gpus: [0]
  batch_size: 16
  lr: 0.0000001
  epochs: 100
  begin_epoch: -1
  warm_up: 6
  every_val_epochs: 1
  loss:
    type: CombinedFocalLoss
    use_target_weight: False
    cls_lmda: 1
    dst_hm_cls_lmda: 0
    offset_lmda: 0
    hm_lmda: 10
    cstency_lmda: 100
    mse_reduction: sum
    ce_reduction: mean
  optimizer: SAM
  distributed: False
  pretrained: ''
  tensorboard: False
  resume: False
  lr_scheduler:
    # type: MultiStepLR
    milestones: [5, 15, 20, 25]
    gamma: 0.5
  freeze_backbone: False
  debug:
    active: False
    save_hm_gt: True
    save_hm_pred: True
TEST:
  gpus: [0]
  subtask: 'eval'
  test_file: ''
  vis_hm: True
  threshold: 0.5
  flip_test: True
  video_level: True
  apr: True # Average precision/recall or normal precision/recall
  no_shot_preds: 1
  pred_file: /project/home/p200249/XXX/saved_predictions/laanet_wBI_DFDC_100_100.json # File to save predictions
  save_preds: False
  pretrained: 'pretrained/PoseEfficientNet_EFN_hm100_EFPN_NoBasedCLS_Focal_C3_256Cst100_8FXRayv2_SAM(Adam)_ADV_Era1_OutSigmoid_5e5_model_best.pth'
